[package]
name = "nix-builtin-utils"
version = "0.2.0"
edition = "2021"
links = "nix-builtin-utils"

[dependencies]

[build-dependencies]
pkg-config = "0.3"

[build-dependencies.cc]
version = "1.0"
features = ["parallel"]
